version: '3'

services:
        bewise_flask:
                build: .
                container_name: bewise_flask_test 
                ports: [80:5000]
                volumes: [.:/usr/src/app]
                depends_on: [pgdb,]
                
        pgdb:
                image: postgres
                environment:
                        - POSTGRES_DB=postgres
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=postgres
                container_name: mypostgres
                
                ports:
                        - 5432:5432
                volumes: 
                        - ./dbdata:/var/lib/postgresql/data

volumes:
        dbdata: 
